### ISSUE TITLE
Get Data from IGDB-API

### ISSUE THREAD

**Issue by pdxphilippmac** [pdxphilippmac/patchfox#10]
- [x] create new page with pathname called Fetch 
- [x] create new icon to represent Fetch in the footer bar
- [x] install axios 
- [x] fetch data from fake api 
- [x] render fetched data on page
- [x] fetch data from igdb.api
- [x] render data on page
- [x] profit

**Comment by cristinamerisoiu** [comment]
gj

**Comment by pdxphilippmac** [comment]
done
